<?php

declare(strict_types=1);

namespace CarmeloSantana\CoquiToolkitSlicedd\Gcode;

use RuntimeException;

/**
 * Parser for G-code files generated by OrcaSlicer/PrusaSlicer.
 *
 * Reads G-code files and extracts structured information:
 * header comments (metadata), layer boundaries, and individual commands.
 */
final class GcodeParser
{
    private const int MAX_HEADER_LINES = 500;
    private const int READ_BUFFER_SIZE = 8192;

    /**
     * Parse a G-code file and return extracted statistics.
     */
    public function parse(string $filePath): GcodeStats
    {
        $this->assertFileReadable($filePath);

        $headerComments = $this->extractHeaderComments($filePath);

        return GcodeStats::fromHeader($headerComments);
    }

    /**
     * Extract key=value pairs from header comments.
     *
     * Looks for lines matching:
     * - `; key = value`
     * - `; key: value`
     * - `; key : value`
     *
     * Scans both the start and end of the file, since OrcaSlicer
     * places some metadata (like estimated time) at the end.
     *
     * @return array<string, string>
     */
    public function extractHeaderComments(string $filePath): array
    {
        $this->assertFileReadable($filePath);

        $comments = [];

        // Parse header (beginning of file)
        $handle = fopen($filePath, 'r');
        if ($handle === false) {
            throw new RuntimeException("Cannot open file: {$filePath}");
        }

        try {
            $lineCount = 0;
            while (($line = fgets($handle)) !== false && $lineCount < self::MAX_HEADER_LINES) {
                $line = trim($line);
                $lineCount++;

                if ($line === '' || !str_starts_with($line, ';')) {
                    // Stop after first non-comment, non-empty line in the header
                    if ($line !== '' && $lineCount > 1) {
                        break;
                    }
                    continue;
                }

                $parsed = $this->parseCommentLine($line);
                if ($parsed !== null) {
                    $comments[$parsed[0]] = $parsed[1];
                }
            }
        } finally {
            fclose($handle);
        }

        // Parse footer (end of file) — OrcaSlicer puts stats here
        $footerComments = $this->extractFooterComments($filePath);
        foreach ($footerComments as $key => $value) {
            $comments[$key] = $value;
        }

        return $comments;
    }

    /**
     * Read all lines from a G-code file as a generator.
     *
     * @return \Generator<int, string>
     */
    public function readLines(string $filePath): \Generator
    {
        $this->assertFileReadable($filePath);

        $handle = fopen($filePath, 'r');
        if ($handle === false) {
            throw new RuntimeException("Cannot open file: {$filePath}");
        }

        try {
            $lineNumber = 0;
            while (($line = fgets($handle)) !== false) {
                yield $lineNumber++ => rtrim($line, "\r\n");
            }
        } finally {
            fclose($handle);
        }
    }

    /**
     * Find layer change positions in the G-code file.
     *
     * OrcaSlicer marks layers with:
     * - `;LAYER_CHANGE`
     * - `; CHANGE_LAYER`
     * - `;BEFORE_LAYER_CHANGE`
     *
     * @return list<array{line: int, z: ?float}>
     */
    public function findLayerChanges(string $filePath): array
    {
        $this->assertFileReadable($filePath);

        $layers = [];

        foreach ($this->readLines($filePath) as $lineNumber => $line) {
            $trimmed = trim($line);

            // OrcaSlicer layer marker
            if (str_starts_with($trimmed, ';LAYER_CHANGE') || str_starts_with($trimmed, '; CHANGE_LAYER')) {
                $layers[] = ['line' => $lineNumber, 'z' => null];
                continue;
            }

            // Try to capture Z height from G1 Z moves following a layer change
            if ($layers !== [] && $layers[array_key_last($layers)]['z'] === null) {
                if (preg_match('/^G[01]\s.*Z([\d.]+)/', $trimmed, $m)) {
                    $layers[array_key_last($layers)]['z'] = (float) $m[1];
                }
            }
        }

        return $layers;
    }

    /**
     * Extract specific G-code commands by type.
     *
     * @param list<string> $commands Command prefixes to match (e.g. ['G28', 'G29', 'M104'])
     * @return list<array{line: int, command: string, full: string}>
     */
    public function findCommands(string $filePath, array $commands): array
    {
        $this->assertFileReadable($filePath);

        $results = [];

        foreach ($this->readLines($filePath) as $lineNumber => $line) {
            $trimmed = trim($line);
            if ($trimmed === '' || str_starts_with($trimmed, ';')) {
                continue;
            }

            // Strip inline comments
            $codePart = strstr($trimmed, ';', before_needle: true) ?: $trimmed;
            $codePart = trim($codePart);

            foreach ($commands as $cmd) {
                if (str_starts_with($codePart, $cmd)) {
                    $results[] = [
                        'line' => $lineNumber,
                        'command' => $cmd,
                        'full' => $codePart,
                    ];
                    break;
                }
            }
        }

        return $results;
    }

    /**
     * Count total lines and command types for quick file overview.
     *
     * @return array{total_lines: int, comment_lines: int, empty_lines: int, command_lines: int, move_commands: int, temp_commands: int, extrusion_commands: int}
     */
    public function countCommands(string $filePath): array
    {
        $this->assertFileReadable($filePath);

        $counts = [
            'total_lines' => 0,
            'comment_lines' => 0,
            'empty_lines' => 0,
            'command_lines' => 0,
            'move_commands' => 0,
            'temp_commands' => 0,
            'extrusion_commands' => 0,
        ];

        foreach ($this->readLines($filePath) as $line) {
            $counts['total_lines']++;
            $trimmed = trim($line);

            if ($trimmed === '') {
                $counts['empty_lines']++;
                continue;
            }

            if (str_starts_with($trimmed, ';')) {
                $counts['comment_lines']++;
                continue;
            }

            $counts['command_lines']++;

            // G0/G1 are movement commands
            if (str_starts_with($trimmed, 'G0') || str_starts_with($trimmed, 'G1')) {
                $counts['move_commands']++;

                // If it has an E parameter, it's an extrusion
                if (preg_match('/\bE[\d.]+/', $trimmed)) {
                    $counts['extrusion_commands']++;
                }
            }

            // Temperature commands
            if (preg_match('/^M(104|109|140|190)\b/', $trimmed)) {
                $counts['temp_commands']++;
            }
        }

        return $counts;
    }

    /**
     * Get a summary of the G-code file: stats, line counts, and layer info.
     *
     * @return array{stats: GcodeStats, counts: array<string, int>, layer_count: int, file_size: int}
     */
    public function analyze(string $filePath): array
    {
        $this->assertFileReadable($filePath);

        return [
            'stats' => $this->parse($filePath),
            'counts' => $this->countCommands($filePath),
            'layer_count' => count($this->findLayerChanges($filePath)),
            'file_size' => filesize($filePath) ?: 0,
        ];
    }

    /**
     * Extract comments from the tail end of a G-code file.
     *
     * @return array<string, string>
     */
    private function extractFooterComments(string $filePath): array
    {
        $fileSize = filesize($filePath);
        if ($fileSize === false || $fileSize === 0) {
            return [];
        }

        // Read the last 8KB of the file
        $readSize = min($fileSize, self::READ_BUFFER_SIZE);
        $handle = fopen($filePath, 'r');
        if ($handle === false) {
            return [];
        }

        $comments = [];
        try {
            fseek($handle, -$readSize, SEEK_END);
            $tail = fread($handle, $readSize);
            if ($tail === false) {
                return [];
            }

            $lines = explode("\n", $tail);
            // Process from bottom to top, stop at first non-comment
            $inFooterComments = true;
            for ($i = count($lines) - 1; $i >= 0 && $inFooterComments; $i--) {
                $line = trim($lines[$i]);

                if ($line === '') {
                    continue;
                }

                if (!str_starts_with($line, ';')) {
                    $inFooterComments = false;
                    continue;
                }

                $parsed = $this->parseCommentLine($line);
                if ($parsed !== null) {
                    $comments[$parsed[0]] = $parsed[1];
                }
            }
        } finally {
            fclose($handle);
        }

        return $comments;
    }

    /**
     * Parse a comment line into key-value pair.
     *
     * @return array{0: string, 1: string}|null [key, value] or null if not a kv comment
     */
    private function parseCommentLine(string $line): ?array
    {
        // Remove leading `;` and optional space
        $content = ltrim(substr($line, 1));

        // Try `key = value` format (OrcaSlicer/PrusaSlicer)
        if (preg_match('/^([^=:]+?)\s*=\s*(.+)$/', $content, $m)) {
            return [trim($m[1]), trim($m[2])];
        }

        // Try `key: value` format
        if (preg_match('/^([^:]+?)\s*:\s*(.+)$/', $content, $m)) {
            $key = trim($m[1]);
            // Skip things like `;TYPE:Outer wall` — those are section markers, not metadata
            if (ctype_upper(str_replace([' ', '_', '-'], '', $key))) {
                return null;
            }
            return [$key, trim($m[2])];
        }

        return null;
    }

    private function assertFileReadable(string $filePath): void
    {
        if (!file_exists($filePath)) {
            throw new RuntimeException("G-code file not found: {$filePath}");
        }
        if (!is_readable($filePath)) {
            throw new RuntimeException("G-code file not readable: {$filePath}");
        }
    }
}
