; generated by OrcaSlicer 2.2.0
; printer_model = Ender-3 S1 Pro
; nozzle_diameter = 0.4
; layer_height = 0.2
; first_layer_height = 0.28
; filament_type = PLA
; nozzle_temperature = 215
; bed_temperature = 60
; wall_loops = 3
; sparse_infill_density = 20%
; total_layer_count = 150
; filament_used [mm] = 4523.45
; filament_used [g] = 13.52
; filament_cost = 0.27
; estimated printing time (normal mode) = 1h 23m 45s

M140 S60 ; set bed temp
M104 S215 ; set nozzle temp
G28 ; home all axes
G29 ; auto bed leveling
M190 S60 ; wait for bed temp
M109 S215 ; wait for nozzle temp
;LAYER_CHANGE
;Z:0.28
;HEIGHT:0.28
G1 Z0.28 F3000
G1 X50 Y50 E5.0 F1500
G1 X100 Y50 E10.0 F1500
G1 X100 Y100 E15.0 F1500
G1 X50 Y100 E20.0 F1500
G1 X50 Y50 E25.0 F1500
;LAYER_CHANGE
;Z:0.48
;HEIGHT:0.2
G1 Z0.48 F3000
G1 X50 Y50 E30.0 F1500
G1 X100 Y50 E35.0 F1500
G1 X100 Y100 E40.0 F1500
G1 X50 Y100 E45.0 F1500
G1 X50 Y50 E50.0 F1500
;LAYER_CHANGE
;Z:0.68
;HEIGHT:0.2
G1 Z0.68 F3000
G0 X60 Y60 F3000 ; travel move
G1 X90 Y60 E55.0 F1500
G1 X90 Y90 E60.0 F1500
G1 X60 Y90 E65.0 F1500
G1 X60 Y60 E70.0 F1500

M104 S0 ; turn off hotend
M140 S0 ; turn off bed
G28 X Y ; home X and Y
M84 ; disable motors

; filament_used [mm] = 4523.45
; filament_used [g] = 13.52
; total_layer_count = 150
; estimated printing time (normal mode) = 1h 23m 45s
; generated_by = OrcaSlicer 2.2.0
