<?php

declare(strict_types=1);

use CarmeloSantana\CoquiToolkitSlicedd\Gcode\GcodeParser;

beforeEach(function () {
    $this->parser = new GcodeParser();
    $this->sampleFile = __DIR__ . '/../fixtures/sample.gcode';
    $this->minimalFile = __DIR__ . '/../fixtures/minimal.gcode';
});

test('parse extracts GcodeStats from sample file', function () {
    $stats = $this->parser->parse($this->sampleFile);

    expect($stats->nozzleTemp)->toBe(215);
    expect($stats->bedTemp)->toBe(60);
    expect($stats->filamentType)->toBe('PLA');
    expect($stats->layerHeight)->toBe(0.2);
    expect($stats->layerCount)->toBe(150);
    expect($stats->filamentUsedMm)->toBe(4523.45);
    expect($stats->filamentUsedG)->toBe(13.52);
    expect($stats->estimatedTimeSeconds)->toBe(5025.0); // 1h 23m 45s
});

test('extractHeaderComments returns key-value pairs', function () {
    $comments = $this->parser->extractHeaderComments($this->sampleFile);

    expect($comments)->toBeArray();
    expect($comments)->toHaveKey('printer_model');
    expect($comments['printer_model'])->toBe('Ender-3 S1 Pro');
    expect($comments)->toHaveKey('nozzle_diameter');
    expect($comments['nozzle_diameter'])->toBe('0.4');
});

test('readLines yields all lines from file', function () {
    $lines = iterator_to_array($this->parser->readLines($this->sampleFile));

    expect($lines)->toBeArray();
    expect(count($lines))->toBeGreaterThan(10);
    expect($lines[0])->toContain('generated by OrcaSlicer');
});

test('findLayerChanges detects layer changes', function () {
    $layers = $this->parser->findLayerChanges($this->sampleFile);

    expect($layers)->toHaveCount(3);
    expect($layers[0]['z'])->toBe(0.28);
    expect($layers[1]['z'])->toBe(0.48);
    expect($layers[2]['z'])->toBe(0.68);
});

test('findCommands locates specific commands', function () {
    $results = $this->parser->findCommands($this->sampleFile, ['G28', 'G29']);

    expect($results)->not->toBeEmpty();

    $commandTypes = array_column($results, 'command');
    expect($commandTypes)->toContain('G28');
    expect($commandTypes)->toContain('G29');
});

test('findCommands returns empty for non-existent commands', function () {
    $results = $this->parser->findCommands($this->sampleFile, ['M600']);

    expect($results)->toBeEmpty();
});

test('countCommands provides correct totals', function () {
    $counts = $this->parser->countCommands($this->sampleFile);

    expect($counts['total_lines'])->toBeGreaterThan(0);
    expect($counts['command_lines'])->toBeGreaterThan(0);
    expect($counts['move_commands'])->toBeGreaterThan(0);
    expect($counts['extrusion_commands'])->toBeGreaterThan(0);
    expect($counts['temp_commands'])->toBeGreaterThan(0);
    expect($counts['comment_lines'])->toBeGreaterThan(0);
});

test('analyze returns comprehensive analysis', function () {
    $analysis = $this->parser->analyze($this->sampleFile);

    expect($analysis)->toHaveKeys(['stats', 'counts', 'layer_count', 'file_size']);
    expect($analysis['layer_count'])->toBe(3);
    expect($analysis['file_size'])->toBeGreaterThan(0);
    expect($analysis['stats']->filamentType)->toBe('PLA');
});

test('parse handles minimal file without metadata', function () {
    $stats = $this->parser->parse($this->minimalFile);

    expect($stats->nozzleTemp)->toBeNull();
    expect($stats->filamentType)->toBeNull();
    expect($stats->layerCount)->toBeNull();
});

test('parse throws on non-existent file', function () {
    expect(fn() => $this->parser->parse('/nonexistent/file.gcode'))
        ->toThrow(\RuntimeException::class, 'not found');
});
